# Generated by Django 3.1.7 on 2021-05-06 19:04

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_ID', models.CharField(default=projects.models.generate_uuid_projects, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('projects_Name', models.CharField(max_length=20)),
                ('clients_Name', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('', '--Please Choose A Status--'), ('WIP', 'Work In Progress'), ('C', 'Completed')], default='', max_length=3)),
                ('date_Created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
