# Generated by Django 3.2 on 2021-04-13 05:33

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=inventory.models.generate_uuid, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
