# Generated by Django 3.2 on 2021-04-14 04:52

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.CharField(default=inventory.models.generate_uuid, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
