# Generated by Django 3.2 on 2021-04-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'For Approval'), (2, 'Approved'), (3, 'Received')], default=1),
        ),
    ]
