# Generated by Django 3.2 on 2021-04-30 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0002_alter_purchasing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='approved_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='requested_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
